import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';
import type { Config } from 'tailwindcss';
import animate from 'tailwindcss-animate';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '16px',
        lg: '24px',
        xl: '24px',
        '2xl': '24px',
      },
      screens: {
        '2xl': '1200px',
      },
    },
    extend: {
      colors: {
        'bg-base': 'var(--color-bg-base)',
        'bg-card': 'var(--color-bg-card)',
        'bg-elevated': 'var(--color-bg-elevated)',
        'accent-gold': 'var(--color-accent-gold)',
        'accent-gold-hover': 'var(--color-accent-gold-hover)',
        'accent-cta': 'var(--color-accent-cta)',
        'accent-cta-hover': 'var(--color-accent-cta-hover)',
        'accent-active': 'var(--color-accent-active)',
        'state-error': 'var(--color-state-error)',
        'state-success': 'var(--color-state-success)',
        'state-warning': 'var(--color-state-warning)',
        'state-info': 'var(--color-state-info)',
        'text-primary': 'var(--color-text-primary)',
        'text-glow': 'var(--color-text-glow)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-disabled': 'var(--color-text-disabled)',
        'vector-aura': 'var(--color-vector-aura)',
        'vector-aura-secondary': 'var(--color-vector-aura-secondary)',
        'vector-jawline': 'var(--color-vector-jawline)',
        'vector-jawline-secondary': 'var(--color-vector-jawline-secondary)',
        'vector-wealth': 'var(--color-vector-wealth)',
        'vector-wealth-secondary': 'var(--color-vector-wealth-secondary)',
        'vector-physique': 'var(--color-vector-physique)',
        'vector-physique-secondary': 'var(--color-vector-physique-secondary)',
        'vector-social': 'var(--color-vector-social)',
        'vector-social-secondary': 'var(--color-vector-social-secondary)',
        'vector-env': 'var(--color-vector-env)',
        'vector-env-secondary': 'var(--color-vector-env-secondary)',
        'level-low': 'var(--color-level-low)',
        'level-mid': 'var(--color-level-mid)',
        'level-high': 'var(--color-level-high)',
        'level-elite': 'var(--color-level-elite)',
        'level-god': 'var(--color-level-god)',
        'rarity-common': 'var(--color-rarity-common)',
        'rarity-rare': 'var(--color-rarity-rare)',
        'rarity-epic': 'var(--color-rarity-epic)',
        'rarity-legendary': 'var(--color-rarity-legendary)',
        'avatar-rastas': 'var(--color-avatar-rastas)',
        'avatar-guarro': 'var(--color-avatar-guarro)',
        'avatar-pecas': 'var(--color-avatar-pecas)',
        'avatar-greñas': 'var(--color-avatar-greñas)',
        'avatar-guero': 'var(--color-avatar-guero)',
        'avatar-lic': 'var(--color-avatar-lic)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        hero: ['3rem', { lineHeight: '1.1', fontWeight: '800' }],
        h1: ['2rem', { lineHeight: '1.2', fontWeight: '700' }],
        h2: ['1.5rem', { lineHeight: '1.3', fontWeight: '600' }],
        h3: ['1.25rem', { lineHeight: '1.4', fontWeight: '600' }],
        body: ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
        small: ['0.875rem', { lineHeight: '1.4', fontWeight: '400' }],
        xs: ['0.75rem', { lineHeight: '1.3', fontWeight: '500' }],
      },
      spacing: {
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-5': '20px',
        'space-6': '24px',
        'space-8': '32px',
        'space-10': '40px',
        'space-12': '48px',
        'space-16': '64px',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        deathShake: {
          '0%,100%': { transform: 'translateX(0)', filter: 'grayscale(100%)' },
          '25%': { transform: 'translateX(-5px)' },
          '75%': { transform: 'translateX(5px)' },
        },
        levelUpGlow: {
          '0%': { boxShadow: '0 0 0 0px rgba(212,175,55,0.4)' },
          '50%': { boxShadow: '0 0 0 20px rgba(212,175,55,0)' },
          '100%': { boxShadow: '0 0 0 0px rgba(212,175,55,0)' },
        },
        vectorPulse: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
          '100%': { transform: 'scale(1)' },
        },
        btcIncrement: {
          '0%': { transform: 'scale(1)', color: 'inherit' },
          '50%': { transform: 'scale(1.2)', color: '#D4AF37' },
          '100%': { transform: 'scale(1)', color: 'inherit' },
        },
        pageEnter: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        pageExit: {
          from: { opacity: '1', transform: 'translateY(0)' },
          to: { opacity: '0', transform: 'translateY(-20px)' },
        },
        streakFire: {
          '0%,100%': { transform: 'scale(1)', filter: 'brightness(1)' },
          '50%': { transform: 'scale(1.1)', filter: 'brightness(1.3)' },
        },
        deathFade: {
          from: { opacity: '1', filter: 'grayscale(0)' },
          to: { opacity: '0.5', filter: 'grayscale(100%)' },
        },
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4,0,0.6,1) infinite',
        shimmer: 'shimmer 2s linear infinite',
        'death-shake': 'deathShake 500ms ease-in-out 3',
        'death-fade': 'deathFade 1s ease-out forwards',
        'level-glow': 'levelUpGlow 1s ease-out',
        'vector-pulse': 'vectorPulse 2s ease-in-out infinite',
        'btc-collect': 'btcIncrement 600ms ease-out',
        'page-enter': 'pageEnter 300ms cubic-bezier(0.4,0,0.2,1)',
        'page-exit': 'pageExit 300ms cubic-bezier(0.4,0,0.2,1)',
        'streak-fire': 'streakFire 1.5s ease-in-out infinite',
      },
    },
  },
  plugins: [typography, forms, animate],
};

export default config;
